//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jbcarreon123.ShareXPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jbcarreon123.ShareXPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PluginStrings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///&lt;__Language__&gt;English&lt;/__Language__&gt;
        ///&lt;__LanguageCode__&gt;en&lt;/__LanguageCode__&gt;
        ///&lt;__Author__&gt;jbcarreon123&lt;/__Author__&gt;
        ///
        ///&lt;AbortScreenRecordingAction&gt;Screen Recording - Abort&lt;/AbortScreenRecordingAction&gt;
        ///&lt;AbortScreenRecordingActionDescription&gt;Abort a screen recording&lt;/AbortScreenRecordingActionDescription&gt;
        ///&lt;ActiveMonitorAction&gt;Screenshot - Active Monitor&lt;/ActiveMonitor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PluginStrings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///&lt;__Language__&gt;Filipino&lt;/__Language__&gt;
        ///&lt;__LanguageCode__&gt;tl&lt;/__LanguageCode__&gt;
        ///&lt;__Author__&gt;jbcarreon123&lt;/__Author__&gt;
        ///
        ///&lt;AbortScreenRecordingAction&gt;Pagre-record ng Screen - I-abort&lt;/AbortScreenRecordingAction&gt;
        ///&lt;AbortScreenRecordingActionDescription&gt;I-abort ang isang screen recording&lt;/AbortScreenRecordingActionDescription&gt;
        ///&lt;ActiveMonitorAction&gt;Screenshot - Aktibong M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Filipino {
            get {
                return ResourceManager.GetString("Filipino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PluginStrings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;__Language__&gt;German&lt;/__Language__&gt;
        ///	&lt;__LanguageCode__&gt;de&lt;/__LanguageCode__&gt;
        ///	&lt;__Author__&gt;jbcarreon123&lt;/__Author__&gt;
        ///	
        ///	&lt;AbortScreenRecordingAction&gt;Bildschirmaufzeichnung - Abbruch&lt;/AbortScreenRecordingAction&gt;
        ///	&lt;AbortScreenRecordingActionDescription&gt;Abbruch einer Bildschirmaufnahme&lt;/AbortScreenRecordingActionDescription&gt;
        ///	&lt;ActiveMonitorAction&gt;Bildschirmfoto - Activ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;PluginStrings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;__Language__&gt;Russian&lt;/__Language__&gt;
        ///	&lt;__LanguageCode__&gt;ru&lt;/__LanguageCode__&gt;
        ///	&lt;__Author__&gt;Senk&lt;/__Author__&gt;
        ///	
        ///	&lt;AbortScreenRecordingAction&gt;Запись Экрана- Отключить&lt;/AbortScreenRecordingAction&gt;
        ///	&lt;AbortScreenRecordingActionDescription&gt;Отключить запись экрана&lt;/AbortScreenRecordingActionDescription&gt;
        ///	&lt;ActiveMonitorAction&gt;Скриншот - Актив.Монитор&lt;/Ac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
    }
}
